import type { Node, Edge } from '@xyflow/react'
import type { NodeData, EdgeData } from '../nodeConfig'

const TF_RESOURCE_MAP: Record<string, string> = {
  ec2:          'aws_instance',
  lambda:       'aws_lambda_function',
  container:    'aws_ecs_task_definition',
  pod:          'kubernetes_pod',
  loadBalancer: 'aws_lb',
  apiGateway:   'aws_api_gateway_rest_api',
  cdn:          'aws_cloudfront_distribution',
  dns:          'aws_route53_record',
  firewall:     'aws_security_group',
  vpn:          'aws_vpn_connection',
  dbSql:        'aws_db_instance',
  dbNoSql:      'aws_dynamodb_table',
  objectStorage:'aws_s3_bucket',
  fileStorage:  'aws_efs_file_system',
  queue:        'aws_sqs_queue',
  eventBus:     'aws_cloudwatch_event_bus',
  pubsub:       'google_pubsub_topic',
  stream:       'aws_kinesis_stream',
  redis:        'aws_elasticache_replication_group',
  memcached:    'aws_elasticache_cluster',
  cdnCache:     'aws_cloudfront_cache_policy',
  k8sCluster:   'aws_eks_cluster',
  ecsCluster:   'aws_ecs_cluster',
  dockerCompose:'docker_container',
  vpc:          'aws_vpc',
  subnet:       'aws_subnet',
  az:           'aws_availability_zone',
  region:       'aws_region',
  namespace:    'kubernetes_namespace',
}

const TF_DEFAULTS: Record<string, string> = {
  aws_instance:                   '  ami           = "ami-0c55b159cbfafe1f0" # TODO: set AMI\n  instance_type = "t3.micro"',
  aws_lambda_function:            '  filename      = "lambda.zip" # TODO: set deployment package\n  handler       = "index.handler"\n  runtime       = "nodejs20.x"',
  aws_lb:                         '  load_balancer_type = "application"\n  internal           = false',
  aws_api_gateway_rest_api:       '  endpoint_configuration {\n    types = ["REGIONAL"]\n  }',
  aws_cloudfront_distribution:    '  default_cache_behavior {\n    viewer_protocol_policy = "redirect-to-https"\n    allowed_methods        = ["GET", "HEAD"]\n    cached_methods         = ["GET", "HEAD"]\n    target_origin_id       = "origin"\n    forwarded_values {\n      query_string = false\n      cookies { forward = "none" }\n    }\n  }\n  restrictions { geo_restriction { restriction_type = "none" } }\n  viewer_certificate { cloudfront_default_certificate = true }',
  aws_db_instance:                '  engine         = "mysql"\n  instance_class = "db.t3.micro"\n  username       = "admin"\n  password       = "changeme" # TODO: use a secret\n  allocated_storage = 20',
  aws_dynamodb_table:             '  billing_mode = "PAY_PER_REQUEST"\n  hash_key     = "id"\n  attribute {\n    name = "id"\n    type = "S"\n  }',
  aws_s3_bucket:                  '',
  aws_sqs_queue:                  '',
  aws_elasticache_replication_group: '  description            = "" # TODO: set description\n  replication_group_id   = "" # TODO: set id\n  node_type              = "cache.t3.micro"\n  num_cache_clusters     = 1',
  aws_eks_cluster:                '  role_arn = "" # TODO: set IAM role ARN\n  vpc_config {\n    subnet_ids = [] # TODO: set subnet IDs\n  }',
  aws_ecs_cluster:                '',
  aws_vpc:                        '  cidr_block = "10.0.0.0/16"',
  aws_subnet:                     '  vpc_id     = "" # TODO: set VPC ID\n  cidr_block = "10.0.1.0/24"',
  kubernetes_namespace:           '  metadata {\n    name = "" # TODO: set namespace name\n  }',
  aws_security_group:             '  ingress {\n    from_port   = 443\n    to_port     = 443\n    protocol    = "tcp"\n    cidr_blocks = ["0.0.0.0/0"]\n  }',
}

function tfIdentifier(label: string, shortId: string): string {
  const base = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    || 'resource'
  return `${base}_${shortId}`
}

export function exportTerraform(
  nodes: Node<NodeData>[],
  edges: Edge<EdgeData>[],
  diagramName: string,
): string {
  const lines: string[] = [
    `# Generated by Scalemap`,
    `# Diagram: ${diagramName}`,
    `# Exported: ${new Date().toISOString()}`,
    ``,
    `terraform {`,
    `  required_version = ">= 1.0"`,
    `  required_providers {`,
    `    aws = {`,
    `      source  = "hashicorp/aws"`,
    `      version = "~> 5.0"`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `provider "aws" {`,
    `  region = "us-east-1" # TODO: set your region`,
    `}`,
  ]

  // Build lookup maps
  const nodeById = new Map(nodes.map(n => [n.id, n]))
  const idToRef = new Map<string, string>()

  // Collect outgoing edges per node
  const outEdges = new Map<string, Edge<EdgeData>[]>()
  for (const e of edges) {
    if (!outEdges.has(e.source)) outEdges.set(e.source, [])
    outEdges.get(e.source)!.push(e)
  }

  // Group nodes by type category for organized output
  const grouped = new Map<string, Node<NodeData>[]>()
  for (const node of nodes) {
    const cat = node.type ?? 'unknown'
    if (!grouped.has(cat)) grouped.set(cat, [])
    grouped.get(cat)!.push(node)
  }

  // Generate resources
  for (const node of nodes) {
    const nodeType = node.type ?? ''
    const data = node.data as NodeData
    const resourceType = TF_RESOURCE_MAP[nodeType]
    if (!resourceType) continue

    const shortId = node.id.split('-')[0]
    const name = tfIdentifier(data.label, shortId)
    idToRef.set(node.id, `${resourceType}.${name}`)

    const defaults = TF_DEFAULTS[resourceType] ?? ''
    const outgoing = outEdges.get(node.id) ?? []
    const deps = outgoing
      .map(e => {
        const target = nodeById.get(e.target)
        if (!target) return null
        const targetType = TF_RESOURCE_MAP[target.type ?? '']
        const targetShortId = target.id.split('-')[0]
        if (!targetType) return null
        return `${targetType}.${tfIdentifier((target.data as NodeData).label, targetShortId)}`
      })
      .filter(Boolean) as string[]

    lines.push(``)
    if (data.notes) {
      for (const noteLine of data.notes.split('\n')) {
        lines.push(`# ${noteLine}`)
      }
    }

    lines.push(`resource "${resourceType}" "${name}" {`)
    if (defaults) lines.push(defaults)

    lines.push(``)
    lines.push(`  tags = {`)
    lines.push(`    Name      = "${data.label}"`)
    if (data.subtitle) lines.push(`    Role      = "${data.subtitle}"`)
    lines.push(`    ManagedBy = "scalemap"`)
    lines.push(`  }`)

    if (deps.length > 0) {
      lines.push(``)
      lines.push(`  depends_on = [`)
      for (const d of deps) lines.push(`    ${d},`)
      lines.push(`  ]`)
    }

    lines.push(`}`)
  }

  // Add outputs for key resources
  const outputTypes = ['aws_instance', 'aws_lb', 'aws_api_gateway_rest_api', 'aws_s3_bucket']
  const outputNodes = nodes.filter(n => outputTypes.includes(TF_RESOURCE_MAP[n.type ?? ''] ?? ''))
  if (outputNodes.length > 0) {
    lines.push(``)
    lines.push(`# ─── Outputs ─────────────────────────────────────────`)
    for (const node of outputNodes) {
      const data = node.data as NodeData
      const rt = TF_RESOURCE_MAP[node.type ?? '']
      const name = tfIdentifier(data.label, node.id.split('-')[0])
      lines.push(``)
      lines.push(`output "${name}_id" {`)
      lines.push(`  value = ${rt}.${name}.id`)
      lines.push(`}`)
    }
  }

  return lines.join('\n')
}
